---

- name: Get update status
  hosts: kiosksOpsRoom
  remote_user: dev

  tasks:
  - name: Update all
    ansible.builtin.dnf:
      name: "*"
      state: latest
    become: true

  - name: Shutdown
    ansible.builtin.command: shutdown