---

- name: Get update status
  hosts: host
  remote_user: bwetteland

  tasks:
  - name: Update all
    ansible.builtin.dnf:
      name: "*"
      state: latest
    become: true

- name: Deplay kiosks
  hosts: newKiosks
  remote_user: dev

  tasks:
  - name: Create user
    ansible.builtin.user:
      name: kiosk
      password: kiosk
    become: true
  
  - name: install software for kiosk
    ansible.builtin.dnf:
      name: 
        - gnome-kiosk
        - gnome-kiosk-script-session
        - zabbix-agent
        - barrier
        - cockpit
      state: latest
    become: true

  # copy over files

  # set firewall
  - name: Open firewall
    ansible.builtin.raw: sudo firewall-cmd --add-service=cockpit --permanent

  - name: Set Zabbix-agent service
    ansible.builtin.service:
      name: zabbix-agent
      enabled: yes
      state: started

  - name: Set cockpit service
    ansible.builtin.service:
      name: cockpit.socket
      enabled: yes
      state: started
